# Generated by Django 5.0 on 2023-12-24 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_slug"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_f_name_68643f_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
